### ISSUE TITLE
Not on OpenVSX

### ISSUE THREAD

**Issue by jalexcole** [1nVitr0/plugin-vscode-valgrind-task-integration#3]
Is there any chance that this plugin could be added to the Open VSX Registry?

**Comment by 1nVitr0** [comment]
Sure, I will take a look into it and if I need to commit any changes to ensure compatibility.

**Comment by jalexcole** [comment]
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

I dont think you will have to do much other than the account process.

**Comment by 1nVitr0** [comment]
@jalexcole So sorry for not publishing this, I simply forgot, although it was onyl a single line of Github Action to add. Should be online in a couple minutes
